project_id = "clillcatrbjzgfaejalg"

[functions.send-notification]
verify_jwt = false

[functions.send-fee-notification]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.reset-password]
verify_jwt = false